[timezone]
name = "Australia/Sydney"

[mqtt]
broker = "azure.nocolor.cc"
port = 1883
username = "feiyue"
password = "123456789"

[topics]
command = "growbox/commands/setpoints"
state = "growbox/state/aggregated"

[co2]
use_fixed = true
fixed_ppm = 400.0

[runtime]
offline_timeout_seconds = 1800
publish_interval_seconds = 900
max_heater_pwm = 100

[sensor_topics]
temperature = "riotee/L_6vSQ/temperature"
co2_ppm = "riotee/L_6vSQ/co2_ppm"
humidity = "riotee/L_6vSQ/humidity"
ppfd_pred = "riotee/L_6vSQ/ppfd_pred"
pn_pred = "riotee/L_6vSQ/pn_pred"
power = "homeassistant/sensor/c1_redblue_power/state"
